
#include "kmod/config.h"

#undef XCONF_XGW_CRYPTO_ALGO_NULL0
#undef XCONF_XGW_CRYPTO_ALGO_NULLX
#undef XCONF_XGW_CRYPTO_ALGO_SUM32
#undef XCONF_XGW_CRYPTO_ALGO_SUM64
#undef XCONF_XGW_CRYPTO_ALGO_SHIFT32_1
#undef XCONF_XGW_CRYPTO_ALGO_SHIFT64_1
#undef XCONF_XGW_CRYPTO_ALGO_SHIFT64_2
#undef XCONF_XGW_CRYPTO_ALGO_SHIFT64_3
#undef XCONF_XGW_CRYPTO_ALGO_SHIFT64_4

#define XCONF_XGW_CRYPTO_ALGO_NULL0 1
#define XCONF_XGW_CRYPTO_ALGO_NULLX 1
#define XCONF_XGW_CRYPTO_ALGO_SUM32 1
#define XCONF_XGW_CRYPTO_ALGO_SUM64 1
#define XCONF_XGW_CRYPTO_ALGO_SHIFT32_1 1
#define XCONF_XGW_CRYPTO_ALGO_SHIFT64_1 1
#define XCONF_XGW_CRYPTO_ALGO_SHIFT64_2 0
#define XCONF_XGW_CRYPTO_ALGO_SHIFT64_3 0
#define XCONF_XGW_CRYPTO_ALGO_SHIFT64_4 1
