
#ifndef XGW
#define XGW_XTUN_ASSERT 1
#define XGW_XTUN_SERVER_IS 1
#define XGW_XTUN_SERVER_PORT 10000
#define XGW_XTUN_NODES_N 256
#define XGW_XTUN_NODE_ID 1
#define XGW_XTUN_PATHS_N 3
#define XGW_XTUN_CRYPTO_ALGO_NULL0 1
#define XGW_XTUN_CRYPTO_ALGO_NULLX 0
#define XGW_XTUN_CRYPTO_ALGO_SUM32 0
#define XGW_XTUN_CRYPTO_ALGO_SUM64 0
#define XGW_XTUN_CRYPTO_ALGO_SHIFT32_1 1
#define XGW_XTUN_CRYPTO_ALGO_SHIFT64_1 0
#define XGW_XTUN_CRYPTO_ALGO_SHIFT64_2 0
#define XGW_XTUN_CRYPTO_ALGO_SHIFT64_3 0
#define XGW_XTUN_CRYPTO_ALGO_SHIFT64_4 1
#endif
